

GENERAL:
  seed: 2021
  log_path: ./logs
  
TRAINING:
  num_k: 4
  learning_rate: 1.0e-4
  num_epochs: 200
  monitor: PearsonCorrCoef
  mode: max
  early_stopping:
    patience: 20
  lr_scheduler:
    patience: 10
    factor: 0.1
  
MODEL:
  model_name: EGN 
  num_outputs: 250

DATA:
  data_dir: input/ST/andrew
  output_dir: output/pred/ST/andrew
  dataset_name: EGNDataset
  gene_type: 'mean'
  num_genes: 1000
  num_outputs: 250
  cpm: True
  smooth: True
  
  train_dataloader:
        batch_size: 128
        num_workers: 4
        pin_memory: False
        shuffle: True

  test_dataloader:
      batch_size: 1
      num_workers: 4
      pin_memory: False
      shuffle: False