

GENERAL:
  seed: 2021
  log_path: ./logs
  
TRAINING:
  num_k: 4
  batch_size: 128
  loss: MSE
  optimizer: adam
  learning_rate: 1.0e-4
  num_epochs: 200
  early_stopping:
    monitor: R
    patience: 20
    mode: max

MODEL:
  name: TRIPLEX 
  num_genes: 250
  emb_dim: 512
  depth1: 2
  depth2: 2
  depth3: 4
  num_heads1: 8
  num_heads2: 16
  num_heads3: 16
  mlp_ratio1: 4
  mlp_ratio2: 1
  mlp_ratio3: 1
  dropout1: 0.1
  dropout2: 0.1
  dropout3: 0.3
  kernel_size: 3
  learning_rate: 0.0001

DATASET:
  data_dir: ./data
  type: skin
  num_neighbors: 5
  t_global_dir: 'gt_features_224'
  n_global_dir: 'gn_features'
  neighbor_dir: 'n_features'
  radius: 224
